// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/mypage.tsx";
import * as $$0 from "./islands/logout.tsx";
import * as $$1 from "./islands/mission.tsx";
import * as $$2 from "./islands/user.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/mypage.tsx": $2,
  },
  islands: {
    "./islands/logout.tsx": $$0,
    "./islands/mission.tsx": $$1,
    "./islands/user.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
